[[intro-python]]
== Знакомство с Python

Python — мощный и простой в использовании язык программирования, разработанный Гвидо ван Россумом (Guido van Rossum). 
Первый релиз системы вышел в 1991 году. 
На Python можно быстро написать небольшой проект, а вообще он применим к проектам любого масштаба, в том числе коммерческим приложениям и программам, нацеленным на ответственные задачи. 
При знакомстве с документацией Python вас может удивить обилие упоминаний про число 42, спам и яйца. 
Все это осталось в память об английском коллективе комических актеров «Монти Пайтон» (Monty Python), в честь которого и был назван язык. 
Хотя Гвидо ван Россум произвел название Python от названия комик-труппы, официальным символом языка стала змейка питон (других вариантов, пожалуй, и не оставалось, ведь значок на Рабочем столе слишком мал, чтобы уместить на нем лица шести английских юмористов).
Существует много других языков программирования. Чем же так привлекателен Python? Судите сами.

=== Python прост в использовании
Базовая цель любого языка программирования — построить «мостик» между мозгом программиста и компьютером. 
Те популярные языки, о которых вы, вероятно, слышали, (Java, Visual Basic, С# и др.) принято называть языками высокого уровня. 
Этот термин предполагает, что они ближе к человеческому языку, чем к машинному. 
Так оно и есть. 
Но Python с его простыми и ясными правилами еще приближается к естественному человеческому (английскому) языку. 
Создание программ на Python настолько незамысловатый процесс, что о нем иногда говорят как о «программировании со скоростью мысли». 
С точки зрения профессионального программиста, легкость Python — залог высокой производительности труда: программы на Python короткие и требуют меньше времени на разработку, чем программы на многих других популярных языках.

=== Python — мощный язык
Python обладает всеми возможностями, которых следует ожидать от современного языка программирования. 
Выполняя задания, вы научитесь пользоваться разнооб-разными структурами данных и писать программы с GUI и файлами состояния.
Благодаря своей мощности Python привлекает разработчиков со всего мира. Им пользуются крупнейшие компании: Google, IBM, Microsoft, NASA, Red Hat, Verizon, Xerox, Yahoo! и др. 
Профессиональные разработчики игр также применяют Python. 
Electronic Arts, 2K Games и Disney Interactive Media Group — все эти компании публикуют игры с кодом на Python.

=== Python — объектно-ориентированный язык
Объектно-ориентированное программирование (ООП) — современный подход к ре-шению задач с помощью вычислительных машин. 
В рамках ООП собственная ин-формация программы и команды, которые она передает компьютеру, записываются интуитивно понятным образом. 
Это, конечно, не единственный способ разработки программ, но в больших проектах, как правило, предпочтительный.
С\#, Java и Python — объектно-ориентированные языки. Но у Python есть пре-имущество перед первыми двумя. 
В С\# и Java ООП-подход проводится неукоснительно. 
Это делает короткие программы избыточно сложными; прежде чем начинающий программист сумеет сделать что-либо толковое, его нужно долго учить языку. 
В Python заложена другая модель: ООП-приемами пользоваться не обязательно. 
Вся их мощь по-прежнему находится в вашем распоряжении, но только вам дано решать, когда именно воспользоваться этой мощью. 
Ваша простенькая программа не требует ООП? 
Все в порядке. 
Ваш большой проект с целой командой программистов жизненно нуждается в ООП? 
Тоже не проблема. 
Python совмещает в себе функциональность и гибкость.

=== Python — «склеивающий» язык
Python легко интегрировать с другими языками, например С, С++ или Java. 
Таким образом, программист на Python может пользоваться разработками, уже имеющимися на других языках, и обращать в свою пользу сильные стороны этих языков (скажем, быстродействие C/C+ + ), не поступаясь простотой разработки — отличительной чертой Python.
 
=== Python работает на всех платформах
Python-программу можно запустить на любой машине: от миниатюрного Palm до суперкомпьютера Cray. 
Если для суперкомпьютера вы недостаточно богаты, то пользоваться Python сможете на ПК с операционной системой Windows, Macintosh, Linux — и это лишь часть списка.
Программы на Python независимы от платформы, то есть неважно, какой опе-рационной системой пользовался разработчик программы: код может быть исполнен на любом компьютере с установленным интерпретатором Python. 
Если, например, вы, работая на PC-совместимом компьютере, написали программу, то ничто не мешает вам переслать копии этой программы другу-линуксоиду и бабушке — обладательнице машины Macintosh. 
Если на компьютерах друга и бабушки установлен Python, программа будет функционировать.

=== Сообщество программистов на Python
Почти каждому языку программирования посвящена хотя бы новостная группа. Среди ресурсов о Python есть особая рассылка Python Tutor, в рамках которой новички могут в свободной форме задавать вопросы о языке. 
Адрес этой рассылки: http://mail.python.org/rnailman/listinfo/tutor. Несмотря на то что в названии есть слово Tutor («наставник»), на вопросы может отвечать кто угодно: и эксперт, и начинающий.
Существуют и другие сообщества, посвященные разным вопросам использования Python. 
Их общая черта в том, что все они чрезвычайно открытые, дружелюбные по отношению к новым участникам. Неудивительно, раз уж язык так прост для освоения с нуля.

=== Python — бесплатная система с открытым исходным кодом
Интерпретатор Python бесплатен. 
Чтобы установить его и пользоваться им, не надо платить ни копейки. 
Лицензия, под которой доступен Python, разрешает и многие другие интересные вещи. 
Можно делать копии Python, в том числе модифицированные. 
Если угодно, можно даже продать Python (но не спешите бросать чтение — вы еще успеете получить свою прибыль!). 
Следование концепции открытого исходного кода — одна из многих особенностей, делающих Python столь популярным и успешным.